# name: aws nuke 

# on:
#   push:
#     branches:
#       - '*'


# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
    
#     # - name: Configure AWS credentials
#     #   continue-on-error: false
#     #   uses: aws-actions/configure-aws-credentials@v1.6.1
#     #   with:
#     #     aws-region: ap-southeast-1
#     #     role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
#     #     role-session-name: run-test
#      - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         role-to-assume: ${{secrets.AWS_IAM_EXAMPLE_ROLE}}
#         aws-region: ap-south-1
#     - name: aws-nuke
#       run: aws-nuke -c nuke-config.yaml


name: aws nuke

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::444964418527:user/pranali
        aws-region: ap-south-1
    
    - name: aws-nuke
      run: aws-nuke -c nuke-config.yaml
