name: AWS nuke

on:
  schedule:
    - cron: '*/1 * * * *'
    - cron: '*/2 * * * *'

jobs:
  morning_job:
    name: Friday Morning Job
    steps:
    - uses: actions/checkout@v2
  evening_job:
    name: Friday Evening Job
    steps:
    - uses: actions/checkout@v2
